config/routes.rb
Rails.application.routes.draw do
  resources :organisations
  resources :orders
  resources :venues
  resources :agendas
  resources :events
  resources :people
  # devise_for :users


  devise_for :users,
    controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
    }

    root to: 'events#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/organisation.rb
class Organisation < ApplicationRecord
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :set_organisation, only: [:show, :edit, :update, :destroy]

  # GET /organisations
  def index
    @organisations = Organisation.all
  end

  # GET /organisations/1
  def show
  end

  # GET /organisations/new
  def new
    @organisation = Organisation.new
  end

  # GET /organisations/1/edit
  def edit
  end

  # POST /organisations
  def create
    @organisation = Organisation.new(organisation_params)

    if @organisation.save
      redirect_to @organisation, notice: 'Organisation was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /organisations/1
  def update
    if @organisation.update(organisation_params)
      redirect_to @organisation, notice: 'Organisation was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /organisations/1
  def destroy
    @organisation.destroy
    redirect_to organisations_url, notice: 'Organisation was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organisation
      @organisation = Organisation.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def organisation_params
      params.require(:organisation).permit(:name)
    end
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/views/organisations/_form.html.haml
= form_for @organisation do |f|
  - if @organisation.errors.any?
    #error_explanation
      %h2= "#{pluralize(@organisation.errors.count, "error")} prohibited this organisation from being saved:"
      %ul
        - @organisation.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/organisations/edit.html.haml
%h1 Editing organisation

= render 'form'

= link_to 'Show', @organisation
\|
= link_to 'Back', organisations_path

app/views/organisations/index.html.haml
%h1 Listing organisations

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @organisations.each do |organisation|
      %tr
        %td= organisation.name
        %td= link_to 'Show', organisation
        %td= link_to 'Edit', edit_organisation_path(organisation)
        %td= link_to 'Destroy', organisation, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Organisation', new_organisation_path

app/views/organisations/new.html.haml
%h1 New organisation

= render 'form'

= link_to 'Back', organisations_path

app/views/organisations/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @organisation.name

= link_to 'Edit', edit_organisation_path(@organisation)
\|
= link_to 'Back', organisations_path