config/routes.rb
Rails.application.routes.draw do
  resources :organisations
  resources :orders
  resources :venues
  resources :agendas
  resources :events
  resources :people
  # devise_for :users


  devise_for :users,
    controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
    }

    root to: 'events#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/agenda.rb
class Agenda < ApplicationRecord
end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
  before_action :set_agenda, only: [:show, :edit, :update, :destroy]

  # GET /agendas
  def index
    @agendas = Agenda.all
  end

  # GET /agendas/1
  def show
  end

  # GET /agendas/new
  def new
    @agenda = Agenda.new
  end

  # GET /agendas/1/edit
  def edit
  end

  # POST /agendas
  def create
    @agenda = Agenda.new(agenda_params)

    if @agenda.save
      redirect_to @agenda, notice: 'Agenda was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /agendas/1
  def update
    if @agenda.update(agenda_params)
      redirect_to @agenda, notice: 'Agenda was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /agendas/1
  def destroy
    @agenda.destroy
    redirect_to agendas_url, notice: 'Agenda was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agenda
      @agenda = Agenda.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def agenda_params
      params.require(:agenda).permit(:title, :start_at, :end_at)
    end
end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/views/agendas/_form.html.haml
= form_for @agenda do |f|
  - if @agenda.errors.any?
    #error_explanation
      %h2= "#{pluralize(@agenda.errors.count, "error")} prohibited this agenda from being saved:"
      %ul
        - @agenda.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :start_at
    = f.datetime_select :start_at
  .field
    = f.label :end_at
    = f.datetime_select :end_at
  .actions
    = f.submit 'Save'

app/views/agendas/edit.html.haml
%h1 Editing agenda

= render 'form'

= link_to 'Show', @agenda
\|
= link_to 'Back', agendas_path

app/views/agendas/index.html.haml
%h1 Listing agendas

%table
  %thead
    %tr
      %th Title
      %th Start at
      %th End at
      %th
      %th
      %th

  %tbody
    - @agendas.each do |agenda|
      %tr
        %td= agenda.title
        %td= agenda.start_at
        %td= agenda.end_at
        %td= link_to 'Show', agenda
        %td= link_to 'Edit', edit_agenda_path(agenda)
        %td= link_to 'Destroy', agenda, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Agenda', new_agenda_path

app/views/agendas/new.html.haml
%h1 New agenda

= render 'form'

= link_to 'Back', agendas_path

app/views/agendas/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @agenda.title
%p
  %b Start at:
  = @agenda.start_at
%p
  %b End at:
  = @agenda.end_at

= link_to 'Edit', edit_agenda_path(@agenda)
\|
= link_to 'Back', agendas_path